# Exploring Data

In [1]:
import pandas as pd
import altair as alt

/Users/gracelynnewest/.pyenv/versions/3.8.5/envs/berkeley_tree_data-3.8.5/lib/python3.8/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [6]:
pd.set_option('display.max_columns', None)

In [2]:
berkeley_trees = pd.read_csv('City_Trees.csv')

In [7]:
berkeley_trees.head()

,the_geom,SiteID,STRT_NUM,STRT_NAM,STRT_ASSIG,BLOCK_ON,SPECIES,ITREE,Common_Nam,OTHER_TREE,ICON_TYPE,LOCATION,GROWSPACE,P_STRIP_WI,SWK_WIDTH,DBH_IN,HEIGHT_FT,SPREAD_FT,STEM_NUM,CONDITION,OBSTREE_ST,OBSTREE_HE,NOTE,ROOTB,TRNK,STAKE_RMV,GRATE,LOW_TREE_W,HVWIRES,HVWIRHT,LVWIRES,MONOSDW,CURB,GUARD,SPACESIZE,TREESIZE,GPS_Date,Vert_Prec,Horz_Prec,Latitude,Longitude,AreaID
0,POINT (-122.27825103970729 37.8849535051094),19143,1161,COLUSA AVE,N,BEVERLY PL,Prunus cerasifera,PRCE,Cherry plum,NaN,T,LEFT,TREE LAWN,4.0,6.0,13.0,30.0,18.0,1.0,20.0,1.0,2.0,"in decline, deadwood, suckers, included bark",N,N,NaN,NaN,NaN,Y,40.0,Y,N,Y,N,3.5,NaN,10/01/2012 07:00:00 AM +0000,0.1,0.1,37.884954,-122.278251,3
1,POINT (-122.27816635887888 37.88496491806563),19144,1161,COLUSA AVE,N,BEVERLY PL,Liquidambar styraciflua,LIST,Sweetgum,NaN,T,LEFT,TREE LAWN,4.0,6.0,7.5,35.0,24.0,1.0,60.0,2.0,3.0,"topped, crowded, sidewalk & road clearance, in...",N,N,NaN,NaN,NaN,Y,40.0,Y,N,Y,N,3.5,NaN,10/01/2012 07:00:00 AM +0000,0.5,0.4,37.884965,-122.278166,3
2,POINT (-122.27803245597467 37.88489176163965),19145,1708,BEVERLY PL,N,BEVERLY PL,Planting Site,NaN,NaN,NaN,P,FRONT,PLANTING SITE,4.0,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,Y,40.0,Y,N,Y,NaN,3.5,SMALL (SDWLK 5 FT),10/01/2012 07:00:00 AM +0000,0.1,0.1,37.884892,-122.278032,3
3,POINT (-122.27795279613872 37.884872693418004),19146,1708,BEVERLY PL,N,BEVERLY PL,Planting Site,NaN,NaN,NaN,P,FRONT,PLANTING SITE,4.0,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,Y,40.0,Y,N,Y,NaN,3.5,SMALL (SDWLK 5 FT),10/01/2012 07:00:00 AM +0000,0.1,0.1,37.884873,-122.277953,3
4,POINT (-122.27787858593904 37.884855236280394),19147,1712,BEVERLY PL,N,BEVERLY PL,Acer species,AC,Maple,NaN,T,FRONT,TREE LAWN,4.0,6.0,1.0,10.0,6.0,1.0,60.0,3.0,3.0,next to power pole,N,N,NaN,NaN,NaN,Y,40.0,Y,N,Y,N,3.5,NaN,10/01/2012 07:00:00 AM +0000,0.1,0.1,37.884855,-122.277879,3

In [4]:
berkeley_trees.tail()

,the_geom,SiteID,STRT_NUM,STRT_NAM,STRT_ASSIG,BLOCK_ON,SPECIES,ITREE,Common_Nam,OTHER_TREE,...,CURB,GUARD,SPACESIZE,TREESIZE,GPS_Date,Vert_Prec,Horz_Prec,Latitude,Longitude,AreaID
46032,POINT (-122.27422705818493 37.871332060519464),33284,1820,M L KING JR WAY,N,M L KING JR WAY,Liriodendron tulipifera,LITU,Tulip tree,NaN,...,N,N,4.0,NaN,12/06/2012 08:00:00 AM +0000,0.1,0.1,37.871332,-122.274227,7
46033,POINT (-122.27442956186094 37.87117125868647),33285,1814,UNIVERSITY AVE,N,UNIVERSITY AVE,Liriodendron tulipifera,LITU,Tulip tree,NaN,...,N,N,4.0,NaN,12/06/2012 08:00:00 AM +0000,0.1,0.1,37.871171,-122.274430,7
46034,POINT (-122.27468758058076 37.87123767665735),33286,1810,UNIVERSITY AVE,N,UNIVERSITY AVE,Planting Site,NaN,NaN,NaN,...,N,NaN,4.0,SMALL (SDWLK 5 FT),12/06/2012 08:00:00 AM +0000,1.3,0.7,37.871238,-122.274688,7
46035,POINT (-122.27478407603465 37.87115416164091),33287,1808,UNIVERSITY AVE,N,UNIVERSITY AVE,Liriodendron tulipifera,LITU,Tulip tree,NaN,...,N,N,4.0,NaN,12/06/2012 08:00:00 AM +0000,0.2,0.1,37.871154,-122.274784,7
46036,POINT (-122.2749554349902 37.87113427284294),33288,1800,UNIVERSITY AVE,N,UNIVERSITY AVE,Liriodendron tulipifera,LITU,Tulip tree,NaN,...,N,N,4.0,NaN,12/06/2012 08:00:00 AM +0000,0.2,0.1,37.871134,-122.274955,7

In [5]:
berkeley_trees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46037 entries, 0 to 46036
Data columns (total 42 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   the_geom    46037 non-null  object
 1   SiteID      46037 non-null  int64
 2   STRT_NUM    46037 non-null  int64
 3   STRT_NAM    46037 non-null  object
 4   STRT_ASSIG  46037 non-null  object
 5   BLOCK_ON    43257 non-null  object
 6   SPECIES     46037 non-null  object
 7   ITREE       35417 non-null  object
 8   Common_Nam  35417 non-null  object
 9   OTHER_TREE  2261 non-null   object
 10  ICON_TYPE   46037 non-null  object
 11  LOCATION    46025 non-null  object
 12  GROWSPACE   46037 non-null  object
 13  P_STRIP_WI  31361 non-null  float64
 14  SWK_WIDTH   39493 non-null  float64
 15  DBH_IN      44851 non-null  float64
 16  HEIGHT_FT   35077 non-null  float64
 17  SPREAD_FT   34801 non-null  float64
 18  STEM_NUM    34802 non-null  float64
 19  CONDITION   35072 non-null  float64
 20  OBSTREE_ST  35065 non-null  float64
 21  OBSTREE_HE  35104 non-null  float64
 22  NOTE        34022 non-null  object
 23  ROOTB       46013 non-null  object
 24  TRNK        45311 non-null  object
 25  STAKE_RMV   3259 non-null   object
 26  GRATE       711 non-null    object
 27  LOW_TREE_W  1561 non-null   float64
 28  HVWIRES     46037 non-null  object
 29  HVWIRHT     15686 non-null  float64
 30  LVWIRES     46037 non-null  object
 31  MONOSDW     46037 non-null  object
 32  CURB        46037 non-null  object
 33  GUARD       29134 non-null  object
 34  SPACESIZE   41608 non-null  float64
 35  TREESIZE    10759 non-null  object
 36  GPS_Date    46037 non-null  object
 37  Vert_Prec   46037 non-null  float64
 38  Horz_Prec   46037 non-null  float64
 39  Latitude    46037 non-null  float64
 40  Longitude   46037 non-null  float64
 41  AreaID      46037 non-null  int64
dtypes: float64(16), int64(3), object(23)
memory usage: 14.8+ MB